name = "worker-template"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-05-19"


[vars]
JKW_URL = ""
MONGO_URL = ""
MONGO_API_KEY = ""
MONGO_DATABASE = ""
MONGO_DATA_SOURCE = ""

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
